### ISSUE TITLE
Is it possible to import this lib via a single script tag?

### ISSUE THREAD

**Issue by hifall** [brijeshb42/monaco-emacs#1]
The default way of importing it is via npm. However, I wonder if there is an easier way to import it via a script tag?

Thanks!

**Comment by brijeshb42** [comment]
Check updated README

**Comment by hifall** [comment]
I did as instructed, but did not find MonacoEmacs inside window.

**Comment by brijeshb42** [comment]
Are you using monaco's `loader.js` file or `requirejs`? If yes, then it won't be available on `window`.

This is what you can do -

```js
// asuming you are setting `vs` path
define('monaco-editor', ['vs/editor/editor.main'], function(monaco) {return monaco;});
define('monaco-emacs', function(MonacoEmacs) {
    // This ^ is what you want
    // init your extension here
});
```

**Comment by brijeshb42** [comment]
See https://github.com/brijeshb42/monaco-emacs#amd if still facing any issue.
