### ISSUE TITLE
"tab" doesn't work

### ISSUE THREAD

**Issue by katlyn-edwards** [brijeshb42/monaco-emacs#3]
In the demo page (https://editor.bitwiser.in/) with "emacs" enabled, `tab` no longer indents text.

This keybinding works in emacs, and should still work on the browser equivalent.

**Comment by brijeshb42** [comment]
You can unregister default keys now starting version `0.2.0` using - 

```js
import { unregisterKey } from 'monaco-emacs';

unregisterKey('Tab');
```
