### ISSUE TITLE
Emacs bindings not working a web app using Monaco Emacs

### ISSUE THREAD

**Issue by kaushalmodi** [brijeshb42/monaco-emacs#7]
Hello,

https://ide.judge0.com/ uses Monaco Editor. The dev @hermanzdosilovic of that project recently added support for Emacs mode.

But while testing that out, I figured out that basic bindings like `C-n`, `C-y`, `C-w`, `C-x h` were not working (so I wasn't able to test out the Emacs mode more thoroughly on judge0.

Ref: https://github.com/judge0/ide/issues/26#issuecomment-550338547

**Comment by hermanzdosilovic** [comment]
Hi @brijeshb42,

it is worth mentioning that this problem can be reproduced on your demo site https://editor.bitwiser.in.

**Comment by brijeshb42** [comment]
https://stackoverflow.com/questions/38838302/any-way-to-override-ctrln-to-open-a-new-window-in-chrome

Ctrl + N, CTRL + W cannot be overridden by javascript as its a core browser feature (won't work on linux and windows but will work on mac as `Ctrl` is free there).
I verified that `C-y` is working and `C-x h` has not been implemented. So I can implement `C-x h` but I'm afraid all other keys will have to be re-mapped to some other combination.
