### ISSUE TITLE
Breaking change in Monaco 0.19.0

### ISSUE THREAD

**Issue by AndrewSverdrup** [brijeshb42/monaco-emacs#8]
The `getConfiguration()` method was recently removed from Monaco which causes this to not work with the latest Monaco version.

See: https://github.com/microsoft/monaco-editor/blob/master/CHANGELOG.md#0190-20122019

**Comment by katlyn-edwards** [comment]
+1; fix should be similar I assume to the fix in monaco-vim: https://github.com/brijeshb42/monaco-vim/issues/45

**Comment by brijeshb42** [comment]
Fixed in #10
